### PR TITLE
Lambda fixes for #186

### PR DESCRIPTION
**Pull request by xdrop**
Hopefully this fixes a few more errors in #186

### CODE REVIEW

**Comment by ftomassetti** [comment]
Thanks again @xdrop , you are putting some great contributions!
Would you be like to to be added as a contributor to the project?

**Comment by xdrop** [comment]
@ftomassetti Sure, thanks!

**Comment by ftomassetti** [comment]
@xdrop I sent you the invitation and I will add your name in the Readme. Should I write "Panayiotis" ?

**Comment by xdrop** [comment]
Many thanks @ftomassetti! I highly appreciate the invitation, and also updated the name to my full name in the readme.

Thanks and looking forward to contribute more!

**Comment by ftomassetti** [comment]
Good usage of your committer powers :D

**Pull request merged**
