### PR TITLE
Fix solving local types

### PR DESCRIPTION
**Pull request by mlangkabel**

### CODE REVIEW

**Comment by ftomassetti** [comment]
Good! I think I have used local classes once in 15+years but it is good to have them covered!
Time for a release

**Comment by mlangkabel** [comment]
Yeah, in Java local types are not used that often, but still, the language accepts those types. I'm currently trying to solve all types in the jp and jss codebases and encountered one unsolvable local type in jp `NodeWithVariables.java`, so I fixed that ;)

**Comment by ftomassetti** [comment]
Good, working on the release right now, after that we could discuss about the priorities for the next cycle

**Comment by matozoid** [comment]
@ftomassetti that local class in that file was created by you :-) Thanks for making JP a better test case!

**Comment by mlangkabel** [comment]
Gotcha!

**Pull request merged**
