### PR TITLE
Implemented parsing nested type parameters and wildcards of JavassistType

### PR DESCRIPTION
**Pull request by mlangkabel**

### CODE REVIEW

**Comment by ftomassetti** [comment]
Wow, looking good. Sorry for the delay in reviewing it.

**Comment by mlangkabel** [comment]
Thanks for merging! I'm currently trying to get rid of all (or at least most of) the remaining `ERROR` and `UNSOLVED` outputs on this branch: [jss060_fixes](https://github.com/javaparser/javasymbolsolver/tree/jss060_fixes). 

I think that's easier and faster than creating a new pull request for each single fix ;)

**Comment by ftomassetti** [comment]
Yes, in this way we can look at each single change singularly, it makes my life much easier. Thank you!

**Comment by mlangkabel** [comment]
Wait, do you mean I **should** create an individual pull request for each fix?

**Comment by ftomassetti** [comment]
Sorry, I misread. Yes, I think it would be when it is not too much extra work for you. I understand that it can be time consuming but if you have small self-contained changes that can be examined separately that would be great. I understand sometimes there are a bunch of inter-connected things or preparing too many small PRs is not worth the effort but when you can do smaller PRs I think it is best.

**Comment by mlangkabel** [comment]
Ok, in that case I'll make small feature branches with individual pull requests for each fix. It'll be some extra work on my part because those fixes may depend on each other and I'l have to maintain one branch that contains the actual pull request and one for further development. But if you are quick with reviewing and merging them that would be great :)

**Comment by mlangkabel** [comment]
Oh, I have an idea: I'll just create one pull request at a time and wait until you reviewed that one before creating the next one. That way I don't have to maintain two branches for each fix. I'll push everything on the jss060_fixes branch so you can see if there are more fixes in the pipeline.

**Pull request merged**
