### PR TITLE
Move to JavaParser 3.2.0

### PR DESCRIPTION
**Pull request by xdrop**
Pain-free move to JavaParser 3.2.0

### CODE REVIEW

**Comment by ftomassetti** [comment]
Great! Time to release then

**Comment by matozoid** [comment]
Did you remember to support receiver parameters? 😁

**Comment by ftomassetti** [comment]
Receiver parameters? Is something new in Java 9?

**Comment by matozoid** [comment]
Java 8 even. Check PR 885.

**Comment by matozoid** [comment]
I think that's automatically supported since it looks like a normal parameter, so never mind.

**Comment by ftomassetti** [comment]
By the way version 0.5.3 is on its way to Maven Central. Thanks a million to all the contributors, in particular to @xdrop , you have been the hero of this release

**Comment by matozoid** [comment]
Yay @xdrop !

**Pull request merged**
