### PR TITLE
In JavaParserTypeSolver, don't assume that class Foo is in a file named Foo.java

### PR DESCRIPTION
**Pull request by batterseapower**
Relevant to #199

### CODE REVIEW

**Comment by ftomassetti** [comment]
I think we could make this behavior configurable, because it is true that it is not necessarily true that a class is in a file with the same name, but that is generally the case. This in most cases save us from having to parse all Java files at once. I would prefer we add a flag to control if to use the old or the new behavior.

And thank you for this very useful contribution!

**Comment by batterseapower** [comment]
I strongly feel that this behaviour should not be configurable. The only reason you might want to turn this off is because of performance considerations, but the performance impact of potentially parsing more files is going to be very low because:

 - The directory traversal + parsing is cached
 - We always start by guessing that the class name and the filename match. Only if that guess fails do we go and look at the rest of the directory. So the only time you pay the performance cost of this feature is when you actually want it to happen.

Even if it was behind a flag I think we would want the flag to be on by default, because this change brings the semantics of JavaSymbolSolver closer to the true semantics of Java and hence is the least surprising default.

**Comment by matozoid** [comment]
Also against making it configurable: this library and JavaParser should aim to do their core jobs 100% correctly.

**Comment by ftomassetti** [comment]
I understand your point of view, is just that I am thinking about how JSS was thought in the beginning: as a complement to JavaParser.

The scenario I had in mind is a user who is parsing something with JavaParser, take a node and want type information on that node. So it call JSS to get quickly an answer. JSS should reply in the shortest time possible. In that scenario it could be surprising if a call to resolve the type _sometimes_ takes way longer because a bunch of files are parsed.

The optimitazion of first guessing the class name is good, however we could have multiple typesolvers, even multiple JavaParserTypeSolver (e.g., one for the real sources, and one for the generated sources). When I try to solve a type on the first and the class is not there as a side effect I would load all files under that directory.

Caching is good but it depends on how many files we have. We are using all sort of caching in JSS and this led to memory issues in the past.

Perhaps we can consider this as an initialization cost: the first call that fail to find the class in the "canonical" position will lead to some extra cost.

I am a big supporter of what works in practice, so let's merge this and see if in real usage scenarios we start getting complaints. If that is the case we will add the flag.

Thank you for working with me on this one.

**Comment by batterseapower** [comment]
Thanks for the merge Federico. I think your approach of waiting to see if we get complaints in practice is a good one.

**Comment by matozoid** [comment]
Sounds like the indexing issue can help with these potential performance problems :)

**Pull request merged**
