### PR TITLE
Moving to JavaParser 3.2.8

### PR DESCRIPTION
**Pull request by ftomassetti**

### CODE REVIEW

**Comment by mlangkabel** [comment]
@ftomassetti: I just noticed your commit to set and increase the available memory for java in travis. Why is this necessary? It it because of the tests?

**Comment by ftomassetti** [comment]
Yes, I keep getting out of memory errors when running tests on Travis. They pass without issues on my machine

**Comment by mlangkabel** [comment]
Hm, I'm getting memory issues when running the tests on my machine, too. I can fix that by adding the following item to the `subprojects` item in the main `build.gradle` file:
```
  test {
    maxHeapSize = "1024m"
  }
```
I thought that this was only an issue on my machine, but as it also fails on the server now, maybe we should add this option to the `build.gradle` file instead of only modifying the travis build.

**Comment by ftomassetti** [comment]
let's try that and I also increased the timeout time on travis. Maybe there is an issue with a new version of JP affecting performance or maybe they changed something on the Travis infrastructure

**Comment by matozoid** [comment]
Hmmm, nothing really huge has been added.
- every node now points to a start and end token. That should be about the same overhead as `range`.
- `CompilationUnit`s save the path of the source if it is known.
- there is a little more lookahead in the grammar

The only way to find out is to analyse memory usage with a tool, I'm afraid.

**Comment by ftomassetti** [comment]
The failures due to timeouts seem to have seen memory issues, so maybe there is just one issue with multiple symptoms. Maybe we have many more token instances? Maybe the parser could do crazy things because of lookahead in some weird cases?

**Comment by matozoid** [comment]
There are pointers to tokens, but there is still only one token list.
You could put an issue on the JP tracker to fix memory issues, but I would really appreciate it if the issue was a concrete problem to solve, not "analyze memory usage" :-)

**Comment by ftomassetti** [comment]
Yes, I see. Well, let's start by merging this one and see. I will create another issue to track the memory problem.

**Comment by ftomassetti** [comment]
The issue for the memory problem investigation is #256

**Pull request merged**
