### PR TITLE
Cache strategy using SoftReferences

### PR DESCRIPTION
**Pull request by bkmeneguello**

### CODE REVIEW

**Comment by ftomassetti** [comment]
I am curious to see how this performs in the real world. If it works well and later we move this portion of code to JavaParser we can replicate some of the Guava features. If not we can always go back to a simple HashMap. What do you think @matozoid ?

**Comment by bkmeneguello** [comment]
This may not be the best option. But, in my case, I had to completely remove cache then my memory don't overflows.
I'm parsing a large source graph with some thousand classes and even with 6GB I run in GC Limit Overhead. After disabling all caching, the entire process runs (slow) but using default memory limits (nothing setted).
The new culprit seems to be JavaParserFacade.cacheWithLambdasSolved and cacheWithoutLambdasSolved, but I don't know how to implement the softReference cache since cacheWithLambdasSolved needs two passes sometimes.

**Comment by matozoid** [comment]
I personally like this as a simple (simplistic?) cache: https://stackoverflow.com/questions/27475797/use-linkedhashmap-to-implement-lru-cache

**Comment by ftomassetti** [comment]
I would be inclined to accept this PR because it requires less code and it does not add new dependencies, with the possibility to move to the approach indicated by @matozoid if we merge into JavaParser. Would this be acceptable @matozoid ?

**Comment by mlangkabel** [comment]
We have evaluated this commit by indexing a the sourcecode of [archi](https://github.com/archimatetool/archi) with Sourcetrail. Before that we had the issue that once the heap was full the indexer would become very slow. This pull request solves that issue.

Moreover it may help to reduce the required memory for running the tests again.

**Comment by matozoid** [comment]
@ftomassetti it's your project, of course it's acceptable :-)

**Comment by ftomassetti** [comment]
It is more our project and anyway it is pointless without JavaParser, so it is better to agree on these things :D

Ok, I am going to merge it and if later we need to the migration I will do the implementation suggested by @matozoid 

Thanks @bkmeneguello for your contribution: it is very appreciated!

**Pull request merged**
